# Generated by Django 6.0.6 on 2026-07-28 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_commentattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_checked', models.BooleanField(default=False)),
                ('admin_checked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_manager_at', models.DateTimeField(blank=True, null=True)),
                ('manager_checked', models.BooleanField(default=False)),
                ('manager_checked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_it_staff_at', models.DateTimeField(blank=True, null=True)),
                ('it_staff_completed', models.BooleanField(default=False)),
                ('it_staff_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_checks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_it_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_staff_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('it_staff_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_staff_completions', to=settings.AUTH_USER_MODEL)),
                ('manager_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_checks', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='tickets.ticket')),
            ],
        ),
    ]
