# Generated by Django 6.0.6 on 2026-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager_it', 'Manager IT'), ('it_staff', 'IT Staff'), ('agent', 'Agent'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
